import { useEffect, useState } from 'react';
import { ArrowUpRight, Bell, ChevronDown, CircleHelp, Clock3, RefreshCw, ShieldCheck, Sparkles, Target, TrendingUp, Users } from 'lucide-react';
import { Badge, Button, Card } from '@sleeper/ui'; import type { LeagueSnapshot, Recommendation } from '@sleeper/domain';
const API=import.meta.env.VITE_API_URL ?? 'http://localhost:4000';
const initials=(name:string)=>name.split(' ').map(n=>n[0]).join('').slice(0,2);
function RecommendationCard({item}: {item: Recommendation}) { const icon=item.kind==='start'?<Target/>:item.kind==='waiver'?<TrendingUp/>:<Users/>; return <article className="recommendation"><div className={`rec-icon rec-icon--${item.kind}`}>{icon}</div><div className="rec-copy"><div className="rec-meta"><span>{item.kind}</span><strong>{item.confidence}% confidence</strong></div><h3>{item.title}</h3><p>{item.rationale}</p><button>{item.actionLabel}<ArrowUpRight size={15}/></button></div></article> }
export function App(){const [data,setData]=useState<LeagueSnapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async(sync=false)=>{setLoading(true);setError('');try{const response=await fetch(`${API}/api/${sync?'sync':'dashboard'}/demo`,{method:sync?'POST':'GET',headers:{Authorization:'Bearer demo-token'}});if(!response.ok)throw new Error('Could not load your league');setData(await response.json());}catch(e){setError(e instanceof Error?e.message:'Something went wrong');}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 return <div className="app-shell"><header className="topbar"><a className="brand" href="#"><span className="brand-mark">H</span><span>HUDDLE</span></a><nav aria-label="Primary navigation"><a className="active" href="#dashboard">Dashboard</a><a href="#roster">My roster</a><a href="#players">Players</a><a href="#league">League</a></nav><div className="header-actions"><button aria-label="Notifications"><Bell size={19}/><i/></button><button className="profile"><span>DM</span><div><strong>Demo Manager</strong><small>Sunday Legends</small></div><ChevronDown size={16}/></button></div></header>
 <main><div className="eyebrow"><span>2026 season</span><span>•</span><span>Week 1</span></div><section className="welcome"><div><h1>Your week, at a glance.</h1><p>Lineup insights and league intelligence—without the noise.</p></div><Button onClick={()=>void load(true)} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Syncing':'Sync league'}</Button></section>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>void load()}>Try again</button></div>}
 {!data?<div className="skeleton" aria-label="Loading dashboard"><div/><div/><div/></div>:<>
 <section className="stat-grid" aria-label="Season summary"><Card><span className="stat-label">Your record</span><strong>{data.record}</strong><small><Badge tone="neutral">Preseason</Badge> Fresh start</small></Card><Card><span className="stat-label">League rank</span><strong>#{data.rank}</strong><small><TrendingUp size={14}/> Projected contender</small></Card><Card><span className="stat-label">Projected score</span><strong>{data.matchup.projectedFor}</strong><small>Opponent <b>{data.matchup.projectedAgainst}</b></small></Card><Card className="accent-card"><div className="stat-label"><span>Win probability</span><CircleHelp size={15}/></div><strong>62<span>%</span></strong><div className="meter"><i/></div></Card></section>
 <div className="content-grid"><div><div className="section-heading"><div><span className="kicker"><Sparkles size={15}/> Game plan</span><h2>Your smartest moves</h2></div><a href="#all">View all <ArrowUpRight size={15}/></a></div><Card className="recommendations">{data.recommendations.map(r=><RecommendationCard key={r.id} item={r}/>)}</Card></div>
 <aside><div className="section-heading"><div><span className="kicker">Week {data.week}</span><h2>Matchup</h2></div><span className="live-dot">Upcoming</span></div><Card className="matchup"><div className="team"><span className="avatar home">DM</span><strong>You</strong><small>{data.leagueName}</small><b>{data.matchup.projectedFor}</b></div><div className="versus"><span>PROJECTED</span><i>VS</i><small>Sun · 1:00 PM</small></div><div className="team"><span className="avatar away">GG</span><strong>{data.matchup.opponent}</strong><small>Opponent</small><b>{data.matchup.projectedAgainst}</b></div></Card>
 <Card className="roster-card"><div className="card-title"><h3>Core starters</h3><a href="#roster">Full roster</a></div>{data.roster.map(p=><div className="player" key={p.id}><span className="player-avatar">{initials(p.name)}</span><div><strong>{p.name}</strong><small>{p.team} · {p.position}</small></div><b>{p.projectedPoints}<small> pts</small></b></div>)}</Card></aside></div>
 <footer><div><ShieldCheck size={16}/><span>Read-only by design. Changes are confirmed and completed in Sleeper.</span></div><div><Clock3 size={15}/>Last synced {new Date(data.lastSyncedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div></footer></>}
 </main></div>}
