import { FormEvent, useMemo, useState } from 'react';
import { AlertCircle, Check, ChevronRight, Clock3, RefreshCw, Search, ShieldCheck, Users } from 'lucide-react';
import type { SleeperLeague, SleeperRoster, SleeperUser } from '@sleeper/sleeper-client';
import { Button, Card } from '@sleeper/ui';
import type { ConnectedLeague } from './dashboard/types';
import { post, request } from './dashboard/api';
type Discovery={seasons:Array<{season:string;leagues:SleeperLeague[]}>;lastSyncedAt:string};type Details={league:SleeperLeague;rosters:SleeperRoster[];lastSyncedAt:string};type Connection={league:SleeperLeague;roster?:SleeperRoster;coOwned:boolean;error?:string};
const api = request;
const avatar=(user:SleeperUser)=>user.avatar?`https://sleepercdn.com/avatars/thumbs/${user.avatar}`:null;const formatSync=(value:string)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
export function ConnectSleeper({ onOpen, onBack }: { onOpen: (league: ConnectedLeague, user: SleeperUser, leagues: ConnectedLeague[]) => void; onBack: () => void }){const year=new Date().getUTCFullYear();const [username,setUsername]=useState('');const [user,setUser]=useState<SleeperUser|null>(null);const [discovery,setDiscovery]=useState<Discovery|null>(null);const [selected,setSelected]=useState<string[]>([]);const [connections,setConnections]=useState<Connection[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [lastSynced,setLastSynced]=useState('');const leagues=useMemo(()=>discovery?.seasons.flatMap(group=>group.leagues)??[],[discovery]);
 const discover=async(candidate=username)=>{setBusy(true);setError('');setConnections(null);try{const account=await api<SleeperUser>(`/api/sleeper/users/${encodeURIComponent(candidate.trim())}`);await post('/api/account/sleeper',{username:account.username,leagueIds:[]});setUser(account);const found=await api<Discovery>(`/api/sleeper/users/${encodeURIComponent(account.user_id)}/leagues?seasons=${year},${year-1},${year-2}`);setDiscovery(found);setLastSynced(found.lastSyncedAt);setSelected([]);}catch(e){setUser(null);setDiscovery(null);setError(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false)}};
 const submit=(event:FormEvent)=>{event.preventDefault();if(username.trim())void discover();};const connect=async()=>{if(!user||!selected.length)return;setBusy(true);setError('');try{await post('/api/account/sleeper',{username:user.username,leagueIds:selected});const results=await Promise.all(selected.map(async id=>{const fallback=leagues.find(item=>item.league_id===id)!;try{const detail=await api<Details>(`/api/sleeper/leagues/${encodeURIComponent(id)}`);const roster=detail.rosters.find(item=>item.owner_id===user.user_id||item.co_owners?.includes(user.user_id));return {league:detail.league,roster,coOwned:Boolean(roster?.co_owners?.includes(user.user_id))} satisfies Connection;}catch(e){return {league:fallback,coOwned:false,error:e instanceof Error?e.message:'Could not load this league.'} satisfies Connection;}}));setConnections(results);setLastSynced(new Date().toISOString());}finally{setBusy(false)}};const refresh=()=>connections?void connect():void discover(user?.username??username);const reset=()=>{setUser(null);setDiscovery(null);setConnections(null);setSelected([]);setError('');setUsername('');};
 return <div className="onboarding-shell"><header className="onboarding-header"><button className="brand-button" onClick={onBack} aria-label="Back to dashboard"><span>H</span>HUDDLE</button><button className="back-to-dashboard" onClick={onBack}>Back to dashboard</button><div className="privacy"><ShieldCheck size={16}/> Secure, read-only connection</div></header><main className="onboarding-main"><div className="intro"><p className="kicker">Connect Sleeper</p><h1>Bring your leagues<br/>into one huddle.</h1><p>Enter your public username, choose the leagues you manage, and we’ll take it from there.</p></div><Card className="connect-card"><div className="steps"><span className="active"><i>1</i>Account</span><b/><span className={user?'active':''}><i>2</i>Leagues</span><b/><span className={connections?'active':''}><i>3</i>Ready</span></div>
 {!user&&<section className="panel"><h2>Find your Sleeper account</h2><p>Use the username shown on your Sleeper profile.</p><form onSubmit={submit}><label htmlFor="username">Sleeper username</label><div className="search-input"><Search size={19}/><input id="username" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="e.g. gridiron_guru"/><Button disabled={busy||!username.trim()}>{busy?<RefreshCw className="spin" size={17}/>:<>Continue <ChevronRight size={17}/></>}</Button></div></form><div className="safe-note"><ShieldCheck size={18}/><div><strong>Your credentials stay private</strong><span>Huddle only uses Sleeper’s public, read-only API. We will never ask for your password or session cookie.</span></div></div></section>}
 {user&&!connections&&<section className="panel"><div className="account-row">{avatar(user)?<img src={avatar(user)!} alt=""/>:<span className="avatar-fallback">{user.display_name[0]}</span>}<div><small>Sleeper account</small><strong>{user.display_name}</strong><span>@{user.username}</span></div><button onClick={reset}>Not you?</button></div><div className="league-heading"><div><h2>Select your leagues</h2><p>Choose one or more NFL leagues to synchronize.</p></div><button className="refresh" onClick={refresh} disabled={busy}><RefreshCw className={busy?'spin':''} size={15}/> Refresh</button></div>{discovery&&leagues.length===0?<div className="empty"><Users/><h3>No leagues found</h3><p>This account has no NFL leagues in the last three seasons. Check the username or join a league in Sleeper first.</p></div>:<div className="season-list">{discovery?.seasons.filter(group=>group.leagues.length).map(group=><section key={group.season}><h3>{group.season} season <span>{group.leagues.length}</span></h3>{group.leagues.map(league=><label className="league-option" key={league.league_id}><input type="checkbox" checked={selected.includes(league.league_id)} onChange={()=>setSelected(ids=>ids.includes(league.league_id)?ids.filter(id=>id!==league.league_id):[...ids,league.league_id])}/><i><Check size={14}/></i><div><strong>{league.name}</strong><span>{league.total_rosters??'—'} teams · {league.status}</span></div></label>)}</section>)}</div>}<div className="card-footer"><span>{selected.length?`${selected.length} league${selected.length===1?'':'s'} selected`:'Select at least one league'}</span><Button disabled={!selected.length||busy} onClick={()=>void connect()}>{busy?<RefreshCw className="spin" size={17}/>:<>Connect leagues <ChevronRight size={17}/></>}</Button></div></section>}
 {connections&&user&&<section className="panel ready"><div className="success-mark"><Check/></div><h2>Your leagues are ready</h2><p>We matched your Sleeper account to its roster in each selected league.</p><div className="connection-list">{connections.map(item=><div key={item.league.league_id} className={item.error||!item.roster?'connection warning':'connection'}><div><strong>{item.league.name}</strong><span>{item.league.season} season</span></div>{item.error?<em><AlertCircle size={15}/> API error — retry refresh</em>:item.roster?<em><Check size={15}/>{item.coOwned?'Co-owned team':'Roster matched'} · #{item.roster.roster_id}</em>:<em><AlertCircle size={15}/> No roster owned by @{user.username}</em>}{item.roster&&!item.error&&<Button onClick={()=>onOpen(item,user,connections)}>Open dashboard <ChevronRight size={15}/></Button>}</div>)}</div><div className="sync-row"><span><Clock3 size={15}/> Last synchronized {formatSync(lastSynced)}</span><Button onClick={refresh} disabled={busy}><RefreshCw className={busy?'spin':''} size={16}/> Refresh now</Button></div></section>}{error&&<div className="form-error" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>void discover()}>Try again</button></div>}</Card><footer>Public league data only · No Sleeper password or cookie required</footer></main></div>}
